version: "3.8"
services:
  backend:
    image: "nsehic/spring-react-application:4.1.2022.10.38.5"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod